// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPLw7Cjm6ZLEMUjcIraRkgUZUk3n6WlSs',
    appId: '1:995024909037:web:f1f9bc537db557e6e652e4',
    messagingSenderId: '995024909037',
    projectId: 'aplikasi-pemantauan-traffic',
    authDomain: 'aplikasi-pemantauan-traffic.firebaseapp.com',
    storageBucket: 'aplikasi-pemantauan-traffic.firebasestorage.app',
    measurementId: 'G-6XXVKCCPGK',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY9FJedYwPookVRyjlWM8kwtHiG-C7Zv4',
    appId: '1:995024909037:ios:9b10f5143825a8eae652e4',
    messagingSenderId: '995024909037',
    projectId: 'aplikasi-pemantauan-traffic',
    storageBucket: 'aplikasi-pemantauan-traffic.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY9FJedYwPookVRyjlWM8kwtHiG-C7Zv4',
    appId: '1:995024909037:ios:9b10f5143825a8eae652e4',
    messagingSenderId: '995024909037',
    projectId: 'aplikasi-pemantauan-traffic',
    storageBucket: 'aplikasi-pemantauan-traffic.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPLw7Cjm6ZLEMUjcIraRkgUZUk3n6WlSs',
    appId: '1:995024909037:web:f30db72b1cea7167e652e4',
    messagingSenderId: '995024909037',
    projectId: 'aplikasi-pemantauan-traffic',
    authDomain: 'aplikasi-pemantauan-traffic.firebaseapp.com',
    storageBucket: 'aplikasi-pemantauan-traffic.firebasestorage.app',
    measurementId: 'G-VS1R9LDBQN',
  );
}
